# Generated by Django 4.2.30 on 2026-05-11 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="优惠码"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("minus", "满减券"),
                            ("discount", "折扣券"),
                            ("fixed", "固定金额券"),
                        ],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="面值/折扣（分或百分比）")),
                (
                    "min_amount",
                    models.IntegerField(default=0, verbose_name="最低消费（分）"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("total", models.IntegerField(default=0, verbose_name="发行总量")),
                ("used", models.IntegerField(default=0, verbose_name="已使用数量")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="是否已使用"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketing.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupons",
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
